export const ACTIONS = {
  /** AUTH ACTIONS START */
  AUTH_TOKEN_START: 'AUTH_TOKEN_START',
  AUTH_TOKEN_SUCCESS: 'AUTH_TOKEN_SUCCESS',
  AUTH_TOKEN_FAILURE: 'AUTH_TOKEN_FAILURE',
  /** AUTH ACTIONS END */
};
